ARG IMAGE=ubuntu
FROM ${IMAGE}
# install build dependencies
RUN apt-get update -qq
RUN apt-get install --no-install-recommends --fix-missing -y \
    gcc autoconf automake libtool git make libyaml-dev libltdl-dev \
    pkg-config check python3 python3-pip python3-setuptools \
    devscripts build-essential lintian debhelper dh-autoreconf fakeroot \
    gnupg \
    latexmk tex-gyre texlive-fonts-recommended texlive-latex-base \
    texlive-latex-recommended texlive-latex-extra
# install sphinx doc dependencies
RUN pip3 install wheel sphinx sphinx_rtd_theme sphinx-markdown-builder linuxdoc
# configure argument
ARG CONFIG_ARGS
ENV CONFIG_ARGS=${CONFIG_ARGS}
COPY . /build
WORKDIR /build
# do a maintainer clean if the directory was unclean (it can fail)
RUN make maintainer-clean >/dev/null 2>&1|| true
RUN ./bootstrap.sh 2>&1
RUN ./configure 2>&1 ${CONFIG_ARGS}
RUN make deb
